# Travis Native

language: r
r:
  - release
  - devel
sudo: required
cache: packages

r_packages: XML

before_install:
  - cd mallet

apt_packages:
 - r-cran-rjava

# Be strict when checking our package
warnings_are_errors: true

r_github_packages:
  -  jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
